# Generated by Django 2.2 on 2020-07-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
    ]
