# Generated by Django 2.2 on 2020-08-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200706_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_type',
            field=models.IntegerField(choices=[(0, '生活'), (1, '工作'), (2, '充电')], default=0),
        ),
    ]
